### ISSUE TITLE
[FIX] (FE) Build 전 Lint 에러 해결

### ISSUE THREAD

**Issue by ykdman** [Programmers-3th-Team-Kim/travel-manager#106]
## Description
FrontEnd 코드 배포를 위한 Build 시,
Lint 설정에 따른 Warning, Error 단계의 코드 삭제 또는 코드 수정 하여 해결

## Task
- [x] frontend/src/api/activities.ts
- [x] frontend/src/components/planDetail/expense/UseCalculateExpenses.tsx
- [x] frontend/src/hooks/useKakaoLogin.ts
- [x] frontend/src/main.tsx
- [x] frontend/src/pages/KakaoLoginPage.tsx
- [x] frontend/src/pages/LoginPage.tsx
- [x] frontend/src/store/auth.ts
