### ISSUE TITLE
[FEAT] (FE) Header 생성

### ISSUE THREAD

**Issue by jellysoo97** [Programmers-3th-Team-Kim/travel-manager#16]
## Description
- 로그인 페이지 외 모든 페이지에서 사용할 Header 컴포넌트 ui
- 라우팅 작업

## Task
- [x] Header 컴포넌트 ui
- [x] react-icons 설치
- [x] 로고, 일정 추가 버튼 라우팅
