### ISSUE TITLE
[FEAT] (BE) plans get method 생성

### ISSUE THREAD

**Issue by uzyhu** [Programmers-3th-Team-Kim/travel-manager#18]
## Description
plans db 생성 및 데이터 가져오기

## Task
- [x] plans 테이블 생성
- [x] travelManager db 연결
- [x] plans 데이터 삽입
- [x] plans 데이터 가져오는 controller & service 생성
