### ISSUE TITLE
[FEAT] (FE) 여행 정보 설정 페이지

### ISSUE THREAD

**Issue by jellysoo97** [Programmers-3th-Team-Kim/travel-manager#26]
## Description
- 여행 정보 페이지 추가
- 공통 Input 컴포넌트 추가
- 공통 Button 컴포넌트 추가

## Task
- [x] 여행 정보 페이지 ui
- [x] 여행 추가 페이지 라우팅 수정
- [x] 공통 Input 컴포넌트 ui
- [x] 공통 Button 컴포넌트 ui
