### ISSUE TITLE
[FEAT] (FE) 공용 axios 요청 함수 작성

### ISSUE THREAD

**Issue by ykdman** [Programmers-3th-Team-Kim/travel-manager#40]
## Description
백엔드 통신시 통일성 있는 request 컨트롤을 위해 공용으로 사용할 수 있는 axiosInstance 함수 작성 필요

## Task
- [x] axios config setting
- [x] header에 자동적으로 accessToken 이 기입되게 설정 ('Authorization')
- [x] 백엔드 endpoint 의 sub url을 자유롭게 넣을 수 있도록 설정
- [x] Method 제한 => "GET", "POST", "DELETE", "PUT" (axios는 Update를 지원하지 않음)
- [x] POST시 Request Body 를 넣을 수 있게 작성
- [x]  Request 와 Response 각 data에 대한 타입을 제네릭 으로 지정할 수 있도록 작성
