### ISSUE TITLE
[FEAT] (FE) 여행 날짜 설정 ui 및 로직 추가

### ISSUE THREAD

**Issue by jellysoo97** [Programmers-3th-Team-Kim/travel-manager#47]
## Description
- 여행 날짜 설정 ui 작업
- 여행 날짜 데이터 변경 로직 추가
- 루트에서 packages 삭제

## Task
- [x] 공통 `DateRangePicker` 컴포넌트 추가
- [x] 여행 날짜 설정 ui
- [x] 출발일, 도착일 데이터 변경 로직 추가
- [x] 루트에서 packages 삭제
