### ISSUE TITLE
[FEAT] (FE) 여행 계획 상세 및 수정 페이지 

### ISSUE THREAD

**Issue by DahyeY** [Programmers-3th-Team-Kim/travel-manager#49]
## Description
여행 계획 상세 수정 페이지 ui 작업
날짜에 따른 일정, 계획, 경비 출력하는 로직 추가
DB에 저장된 데이터 받아와서 적용하기

## Task
- [ ] 배열로 들어있는 여행 계획을 일자에 따라 map으로 구현
- [ ] DB 내에 저장된 데이터 끌어오기
- [ ] DB에 계획 입력, 수정, 삭제
