### ISSUE TITLE
[FEAT] (FE) 여행지, 날짜 추가 단계 통합

### ISSUE THREAD

**Issue by jellysoo97** [Programmers-3th-Team-Kim/travel-manager#51]
## Description
- 기존 로직: 날짜 선택 -> 일수만큼 여행지 선택 폼 생성 -> 하루씩 여행지 선택
- 변경 로직: 여행지 선택 -> 해당 여행지에서 머무르는 기간 설정 -> 기간 최솟값 = 전체 여행 출발일, 기간 최댓값 = 전체 여행 도착일

## Task
- [x] 여행 추가 페이지 구조 변경
- [ ] 공통 Modal 컴포넌트 추가
- [ ] 여행지, 날짜 선택 단계 ui
- [ ] 여행지, 날짜 선택 단계 로직 추가
