### ISSUE TITLE
[FEAT] (BE) : get '/city/:id' api 구현

### ISSUE THREAD

**Issue by uzyhu** [Programmers-3th-Team-Kim/travel-manager#65]
## Description
이슈 설명
- get '/city/:id' api 구현
- response로 city_name, country_name 출력하기
## Task
- [x] city 모듈 생성
- [x] country 모듈 생성
- [x] city service -> findOne으로 city_name과 country_name 가져오기
