### ISSUE TITLE
[FIX] (FE) api request, response dto 타입 수정

### ISSUE THREAD

**Issue by jellysoo97** [Programmers-3th-Team-Kim/travel-manager#69]
## Description
api request, response dto대로 타입 수정 [참고](https://www.notion.so/prgrms/Back-End-6e9200d0959e4931b47d58f2e64f7400)

## Task
- [x] dto 타입 수정
- [x] dto 타입 적용
- [x] 더미 데이터 생성
