### ISSUE TITLE
(BE) 계획 CRUD API 구현

### ISSUE THREAD

**Issue by ykdman** [Programmers-3th-Team-Kim/travel-manager#8]
## Description
- 계획 생성, 조회, 삭제, 수정 API 구현

## Task
- [ ] plans Table 구축 (DB)
- [ ] `GET` /api/plans 기능 구현 : 계획 조회
- [ ] `POST` /api/plans 기능 구현 : 계획 생성
- [ ] `PUT` or `PATCH` /api/plans/:planId 기능 구현 : 계획 수정
- [ ] `DELETE` /api/plans/:planId 기능 구현 : 계획 삭제

**Comment by ykdman** [comment]
@leemh98 
민형님 담당 BE 관련 Issue 입니다!
추가 작성 하신다면 코멘트로 달아주세요 제가 수정해놓겠습니다!
