### ISSUE TITLE
(FE) 메인 페이지 구현

### ISSUE THREAD

**Issue by ykdman** [Programmers-3th-Team-Kim/travel-manager#9]
## Description
- 클라이언트 메인 화면 마크업

## Task
- [ ] 모바일 레이아웃 마크업
- [ ] 웹 레이아웃 마크업
- [ ] Session 내 Access Token 미존재시 /signin 리다이렉트 기능 구현
- [ ] Session 내 Access Token 존재 시 `GET` /api/plans 를 통한 계획 리스트 마크업

**Comment by ykdman** [comment]
@uzyhu 
지후님 ! 추가로 어떤 부분 필요한지 몰라서 더 안적었습니다!
추가로 필요한 부분 말씀해주시면 Edit 할게요!
